pipeline {
    agent { label 'fedora31 || fedora32' }

    options {
        timestamps()
        ansiColor('xterm')
    }

    // Get quay.io credentials.
    environment {
        QUAY_CREDS = credentials('schutzbot-quay')
    }

    // Build new containers on weekdays.
    triggers {
        cron('H 0 * * 1-5')
    }

    stages {
        stage("build") {
            parallel {

                stage('ansible') {
                    environment { CONTAINER_NAME = 'ansible' }
                    steps { sh "schutzbot/build.sh" }
                }

                stage('fedora31') {
                    environment { CONTAINER_NAME = 'osbuild-fedora31' }
                    steps { sh "schutzbot/build.sh" }
                }

                stage('fedora32') {
                    environment { CONTAINER_NAME = 'osbuild-fedora32' }
                    steps { sh "schutzbot/build.sh" }
                }

                stage('fedora33') {
                    environment { CONTAINER_NAME = 'osbuild-fedora33' }
                    steps { sh "schutzbot/build.sh" }
                }

                stage('rhel82') {
                    environment { CONTAINER_NAME = 'osbuild-rhel82' }
                    steps { sh "schutzbot/build.sh" }
                }

            }

            post {
                always {
                    sh "buildah logout --all || true"
                }
            }

        }
    }
}